### ISSUE TITLE
Fancy console is not cleared if .cls() is the only operation

### ISSUE THREAD

**Issue by nicolaracco** [amethyst/bracket-lib#278]
Following the Hands On Rust's first chapter, I implemented the "Flappy Dragon" game. After that I followed this post https://hands-on-rust.com/2021/02/08/from-flappy-dragon-to-flappy-bonus/ to improve it, obtaining this: https://gist.github.com/nicolaracco/18d6ed34571f8f4cf4a42b39457f38a1

But I noticed that when the player hits an obstacle, it is still rendered on screen, so I added a ctx.cls() call on the dead function: https://gist.github.com/nicolaracco/18d6ed34571f8f4cf4a42b39457f38a1#file-flappy_dragon-rs-L135

But even with this call, when the "You are dead" screen is shown, the dragon sprite stays on screen. If I add any other draw call (like another ctx.set_fancy call), the problem disappears (but I would not to draw anything in this case :))

**Comment by thebracket** [comment]
I *think* this is fixed in the current Github version; there is a "set dirty" call (indicating that it needs redrawing) in place. Would you mind switching your project to try the current build?

In `Cargo.toml` you can replace:
```toml
bracket-lib = "0.8"
```

with 

```toml
bracket-lib = { git = "https://github.com/amethyst/bracket-lib.git" }
```

In the interim, I'll see if I can cook up a test case to be sure.

**Comment by patchfx** [comment]
@thebracket The problem still exists in the current master branch. I patched this locally by changing the `cls()` function in `FancyConsole` .

```rust
    fn cls(&mut self) {
        self.is_dirty = true;
        for tile in &mut self.tiles {
            tile.glyph = 32;
            tile.fg = RGBA::from_u8(255, 255, 255, 255);
            tile.bg = RGBA::from_u8(0, 0, 0, 255);
        }
    }
```

This effectively replicates the behaviour of a simple console. I didn't open a PR as I was following the related thread #255 

Hope this helps!

**Comment by nicolaracco** [comment]
Sorry for the delay. Anyway, @patchfx is right and his workaround works

**Comment by thebracket** [comment]
I've applied this patch, it looks like it worked from here - thank you!

**Comment by nicolaracco** [comment]
I'm not sure if it's strictly related to this issue or if I should open a new one, but when using two different consoles, each cls seems to "paint" in the background.
![image](https://user-images.githubusercontent.com/203857/183930497-fb36e09e-f2b1-4b18-8d67-6513b8223e9e.png)

In this case, the console 0 draws a NAVY background, the console 1 just draws the player sprite, without setting any background. Each .cls() call seems to clear the sprite, but replacing it with a black background.

Is it expected and I'm missing something?

**Comment by bilowik** [comment]
Yeah I think this poses an issue when Flexiconsole is not the bottom layer, it will leave permanent black bg on tiles that cover consoles under it. Changing the alpha values from 255 to 0 in those .cls() methods fixed that for me, but not sure if that's the correct fix or just happens to bandaid my specific issue.
